### ISSUE TITLE
Refactor `ConsoleDriver` to minimize duplicated code in all drivers

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2319]
As illustrated by 

- #2318 (and many other examples)

...the design of `ConsoleDriver` has resulted in all of the sub-classes to have tons of duplicated code. In v2 we should refactor `ConsoleDriver` to fix this as much as possible. 

## Todos

- [x] Most drawing stuff has been consoldated
  - [x] `AddRune`
  - [x] `UpdateScreen`
  - [x] `Color/Attribute` stuff 
- [ ] #3119 - (IOW, there's more to do in reducing duplicate keyboard related code).
- [ ] #3029 - (Mouse stuff is still massively duplicated)

**Comment by tig** [comment]
Partially fixed by #2320 - much more to do.
