### ISSUE TITLE
`EnsureVisibleBounds` is complex & confusing

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2407]
This is a sub-issue of:

- #2994 

## Todo

- [x] Move out of `Toplevel` to `View` and make `static` (Fixed in https://github.com/gui-cs/Terminal.Gui/pull/3278)
- [x] Make `internal`. (Fixed in https://github.com/gui-cs/Terminal.Gui/pull/3278)
- [ ] Remove dependency on menu/status bar (via #2488)
- [ ] Make it optional. In some use-cases, being able to move a view beyond Bounds makes sense.

**Comment by BDisp** [comment]
@tig yes you right. It is very buggy. I think we can fix this in v1 and I submitted the PR https://github.com/tig/Terminal.Gui/pull/11 with the fix. With that fix we can have any number of nested `Window` with menu and status bar. See the unit test.

![toplevel-fix](https://user-images.githubusercontent.com/13117724/224566456-fb824fb4-a38e-4813-b013-92c8827f5b8c.gif)

**Comment by tig** [comment]
This is partially fixed.
