### ISSUE TITLE
Refactor `MenuBar` and `StatusBar` to be adornments

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2488]
This is a sub-issue of:

- #2994 

## Todo

- [ ] Reimplemen these views based on `Bar`. See https://github.com/gui-cs/Terminal.Gui/issues/3073
- [ ] Remove the dependency between these classes and `Toplevel` and enable any view to host a menubar or statusbar (or any View).
- [ ] By default `Window` will have the menubar and statusbar's added to  it's `Border/Adornment` `Frame` but they will be `Visible = false` by default. We'll expose helper properties to access them:

`win.MenuBar.Visible = true` etc...

**Comment by tig** [comment]
Not entirely sure this is needed.

**Comment by BDisp** [comment]
> Not entirely sure this is needed.

I don't think this make senses because any view has adornments and the question must be  should `MenuBar` and `StatusBar` be created in the parent adornments? Now it's possible to add it anywhere the user want it, right? If affirmative then this can be closed.

**Comment by tig** [comment]
I had two reasons for suggesting this:

1) Views can't render outside of their Viewport. That's a new LAW for v2. But the same law does not apply to Adornments because they are system managed. Menu, in particular, has the need to render outside of the Viewport because a dropdown may be larger than the view. 

2) The `Toplevel` code that tries to be "smart" about Menu/Statusbar is clumsy and bug ridden. I was thinking putting them in Padding might enable this to be simplified.

I still think 1) is semi-valid. I don't think 2) is valid anymore.

I'm going to close this for now though as there's not enough justification.
