### ISSUE TITLE
Adornments: Enable SubViews in `Margin`, `Border`, and `Padding`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2563]
This is a sub-issue of:

- #2994 

## Todo

- [x] What happens when `Adornment.Add` is called? Fixed in #3278 
  * Nothing special happens, but the various layout and draw methods now do the right thing.
  *  The thickness is not automatically adjusted. 
- [x] How should `MouseEvent`s work? Fixed in #3278 
- [ ] How should `Focus` work? Because `Padding` is in a different view hierarchy from the dialog, `Tab` etc... doesn't tab into the buttons. 
    *  `Padding` - Any views added to `Padding` are included in `Padding.Parent`'s focus chain. If `View.Subviews[^1].HasFocus` and the user presses `Tab` `Padding.SubViews[0]` will get focus. Etc...
    * `Border` - `Ctrl-F10` is used to set focus on `Border.Subviews[0]`. Subsequent `Tab` presses cycle through `Border.Subviews`. `Ctrl-F10` again returns focus to `Border.Parent`.
    * `Margin` - No default behavior. If someone adds views to `Margin` they are on their own to figure out a focus model (I can't think of any use case where it makes sense to add a subview to `Margin`.

## Background

  * Examples of SubViews in Adornments:
    * A `TitleBar` renders the View's `Title` and a horizontal line defining the top of the View. Added to `Border`.
      * One or more `LineView`s that render the View's 'Border` 
    * A `Vertical Scrollbar` adds thickness to `Padding.Right` (or `.Left` when right-to-left language support is added). 
    * A `Horizontal Scrollbar` adds thickness to `Padding.Bottom` when enabled.
    * A `MenuBar` adds thickness to `Padding.Top` (NOTE: This is a change from v1 where `subview.Y = 1` is required).
    * A `StatusBar` adds thickness ot `Padding.Bottom` and is rendered at the bottom of `Padding`.
    * In `Dialog` (and derived classes), the buttons can be added to `Padding` (`Y = Pos.AnchorEnd(1)`).

* Should expanding of, e.g. `Padding.Thickness` be automatic when `Padding.Add` is called? If `Dim.Auto` is implemented, it might be possible for this to happen. For now: I suggest devs adding adornments manually expand thickness as appropriate. In my Dialog prototype, I did this:

```cs
		public void AddButton (Button button)
		{
			if (button == null) {
				return;
			}
			
			_buttons.Add (button);
			Padding.Thickness = new Thickness (Padding.Thickness.Top, Padding.Thickness.Left, Padding.Thickness.Right, 1);
			Padding.Add (button);
			LayoutButtons ();
		}
```

**Comment by tig** [comment]
> How you think on handling the `StatusBar` and a `ScrollBar` on `Padding`? If a `StatusBar` exists then the `ScrollBar` should be above, right? 

Yes, I think that's right. 

This reminds me of something else I was thinking about:

`Thickness` needs rules around which edges have precedence, by default. 

E.g. which is more true, given `view.Padding.Thickness = new Thickness(1); view.Width = 10; view.Height = 10;`:

- `Padding.Top.Width == 10` and `Padding.Left.Height == 10`
OR
- `Padding.Top.Width == 10` and `Padding.Left.Height == 8`

Note, I do NOT mean `Padding.Left.Height` should be different if `Padding.Top/Bottom > 0` literally; just to illustrate something that could be very confusing. 

Regardless, here's how I think we'd lay out a `View` with all four adornments:

```cs
Padding.Thickness = new Thickness (
  _menuBar.Visible ? 1 : 0,    // Top
  0,  // Left
  _verticalScrollBar.Visible ? 1: 0,  // Right
  (_statusBar.Visible ? 1 : 0) + (_horizontalScrollBar.Visible ? 1 :0));  // Bottom

// These have all been `Padding.Add()`ed
_menuBar.X = 0;
_menuBar.Y = 0;
_menuBar.Width = Dim.Fill();
_menuBar.Height = 1;

_statusBar.X = 0;
_statusBar.Y = Pos.AnchorEnd (1);
_statusBar.Width = Dim.Fill();
_statusBar.Height = 1;

_verticalScrollbar.X = Pos.AnchorEnd(1);
_verticalScrollbar.Y = _menuBar.Visible ? Pos.Bottom (_menuBar) : 0;
_verticalScrollbar.Width = 1;
_verticalScrollbar.Height = Dim.Fill ((_menuBar.Visible ? 1 : 0) + (_statusBar.Visible ? 1 : 0) + (_horizontalScrollBar.Visible ? 1 : 0));

_horizontalScrollbar.X = 0;
_horizontalcrollbar.Y = Pos.AnchorEnd (_statusBar.Visible ? 2 : 1);
_horizontalScrollbar.Width = Dim.Fill ();
_horizontalScrollbar.Height = 1;
```

**Comment by BDisp** [comment]
> * In `Dialog` (and derived classes), the buttons can be added to `Padding` (`Y = Pos.AnchorEnd(1)`).

And in the cases where we want buttons arbitrary on others locations, that possible, right? Added to `Padding` you only mean the ones that are passed by the `params`, right?

**Comment by tig** [comment]
> > * In `Dialog` (and derived classes), the buttons can be added to `Padding` (`Y = Pos.AnchorEnd(1)`).
> 
> And in the cases where we want buttons arbitrary on others locations, that possible, right? Added to `Padding` you only mean the ones that are passed by the `params`, right?

Correct. 

On the same note, for `Wizard` I plan on putting the `HelpText` view (a `TextView` that is set to readonly) in `Padding`:

```cs
Padding.Thickness = new Thickness (Padding.Thickness.Top, Padding.Thickness.Left, Padding.Thickness.Right, 1);
_helpText.X = Pos.AnchorEnd (1);
_helpText.Y = 0;
_helpText.Width = 15; 
_helpText.Height = Dim.Fill (2); // +1 for buttons on Bottom
Padding.Add (_helpText);
```

**Comment by tig** [comment]
A key part of addressing this issue will be:

* enable `Margin`, `Border`, `Padding` to be overridden/replaced by a `View` derivative

Less important (and highly debatlve), but interesting. Including this just to make sure we are intentional:

* enable `Margin`, `Border`, `Padding` to be overriden/replaced by a user of a `View`.

**Comment by BDisp** [comment]
> A key part of addressing this issue will be:
> 
> * enable `Margin`, `Border`, `Padding` to be overridden/replaced by a `View` derivative
> 
> Less important (and highly debatlve), but interesting. Including this just to make sure we are intentional:
> 
> * enable `Margin`, `Border`, `Padding` to be overriden/replaced by a user of a `View`.

Just to remember that you may want to join `LineCanvas` through a View (`Margin`, `Border`, `Padding`) but not with others views.

**Comment by tig** [comment]
> > A key part of addressing this issue will be:
> > 
> > * enable `Margin`, `Border`, `Padding` to be overridden/replaced by a `View` derivative
> > 
> > Less important (and highly debatlve), but interesting. Including this just to make sure we are intentional:
> > 
> > * enable `Margin`, `Border`, `Padding` to be overriden/replaced by a user of a `View`.
> 
> Just to remember that you may want to join `LineCanvas` through a View (`Margin`, `Border`, `Padding`) but not with others views.

If I understand you correctly, this is what `SuperViewRendersLineCanvas` is for.
