### ISSUE TITLE
Update CI/CD for V2

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2699]
- [x] Update yml to latest v1 stuff
- [x] Make `v2_develop` primary branch
  - [x] Ensure v1 releases can still work
  - [x] Backport any changes to v1 docs/readmes etc... that may have been missed
- [ ] Make V2 API docs primary API docs (https://github.com/gui-cs/Terminal.GuiV2Docs -> https://github.com/gui-cs/Terminal.GuiV1Docs).

What else?

## Todo

- [x] Fix #3052 
- [x] Update YML to match v1 where needed
- [x] Ensure nuget packages from `v2_develop` are still being published correctly as `2.0.0-pre.xxxx`
- [x] Ensure nuget packages from `v2` are published correctly as `2.0.0-prealpha.xxxx`
- [x] Fix #873
- [x] Do a "last release" of v1 where `develop` is primary
- [x] Update `main` to match `develop` - `main` will remain the "currently released" branch forever - this means it will hold `v1` until `v2` is out of Beta.
- [x] Change `v2_develop` to be primary github branch
- [x]  Do a "test release" from `develop` to ensure releasing still works

**Comment by dodexahedron** [comment]
Just an ack that I saw this one.

No immediate commentary though, other than 👍
